FROM postgres:17-alpine

RUN apk add --no-cache gzip dcron

COPY backup.sh /backup.sh
RUN chmod +x /backup.sh

ENV CRON_SCHEDULE="0 3 * * *"

COPY crontab-entrypoint.sh /crontab-entrypoint.sh
RUN chmod +x /crontab-entrypoint.sh

ENTRYPOINT ["/crontab-entrypoint.sh"]
